import React from "react";
import { Link } from "react-router-dom";
import Nav from "../components/Nav.jsx";

export default function TermsPage() {
  return (
    <div className="min-h-screen text-ink">
      <Nav />
      <div className="max-w-[720px] mx-auto px-6 pb-20">
        <div className="pt-8 pb-12">
          <div className="text-accent2 text-xs font-semibold tracking-widest uppercase mb-3">Legal</div>
          <h1 className="font-display text-4xl mb-3">Terms of Service</h1>
          <p className="text-muted text-sm">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
        </div>

        <div className="space-y-8 text-sm text-muted leading-relaxed">
          <section>
            <h2 className="font-display text-lg text-ink mb-3">1. Service description</h2>
            <p>MatchMaker AI is an AI-powered dating profile analysis tool. We provide feedback and suggestions to help you improve your dating profile. Results are generated by AI and are for guidance purposes only — we make no guarantee of improved match rates or dating outcomes.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink mb-3">2. Eligibility</h2>
            <p>You must be 18 years of age or older to use this service. By using MatchMaker AI, you confirm that you are at least 18 years old.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink mb-3">3. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 ml-2">
              <li>Upload images of minors or anyone without their consent</li>
              <li>Upload explicit, offensive, or illegal content</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the service</li>
              <li>Use the service for any unlawful purpose</li>
              <li>Upload images that do not belong to you</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink mb-3">4. Payments and refunds</h2>
            <p>The full audit is available for a one-time fee of $4.99 per profile. All payments are final. We do not offer refunds once the full audit has been delivered, as the AI analysis has already been completed. If you experience a technical issue that prevents you from accessing your paid results, contact us and we will resolve it.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink mb-3">5. AI-generated content</h2>
            <p>All analysis, scores, feedback, and rewritten bios are generated by AI. They reflect the AI's interpretation of your profile and should be treated as suggestions, not professional advice. MatchMaker AI is not a substitute for professional coaching or counselling.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink mb-3">6. Limitation of liability</h2>
            <p>MatchMaker AI is provided "as is" without warranty of any kind. We are not liable for any damages arising from your use of the service, including but not limited to loss of data, loss of profits, or any indirect or consequential damages.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink mb-3">7. Changes to these terms</h2>
            <p>We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink mb-3">8. Contact</h2>
            <p>For any questions regarding these terms, please contact us at the email address listed on our website.</p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-white/08 flex gap-6">
          <Link to="/" className="text-muted text-xs hover:text-ink transition-colors">← Back to home</Link>
          <Link to="/privacy" className="text-muted text-xs hover:text-ink transition-colors">Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}
